import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import { Poppins } from 'next/font/google'
import Header from '@/components/Header'
import HeaderMobile from '@/components/HeaderMobile'

const heavitas = localFont({
  src: './fonts/Heavitas.woff',
  variable: '--font-heavitas',
  weight: '100 900',
})

const tomatoes = localFont({
  src: './fonts/Tomatoes.ttf',
  variable: '--font-tomatoes',
  weight: '100 900',
})

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  variable: '--font-poppins',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`${heavitas.variable} ${tomatoes.variable} ${poppins.variable} antialiased`}>
        <Header />
        <HeaderMobile />
        {children}
        <div className='h-[100rem]'></div>
      </body>
    </html>
  )
}
